In [1]:
import numpy as np

In [2]:
dataFile="data/D2_Achilles_gene_dep_scores.tsv"
dataRawStrs = np.loadtxt(dataFile, dtype='str', delimiter="\t")

In [3]:
print(dataRawStrs.shape)

(16756, 502)


In [4]:
unitTestData = dataRawStrs[0:5, 0:5]
print(unitTestData)

[['""' '"143B_BONE"' '"22RV1_PROSTATE"' '"2313287_STOMACH"'
  '"697_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE"']
 ['"A1BG (1)"' '0.0524661469433624' '-0.115242032403861'
  '-0.0231724479806354' '-0.0233374641152424']
 ['"NAT2 (10)"' '0.0841725922071565' '0.000951246047267534'
  '-0.154187814972645' '-0.0790055310659458']
 ['"ADA (100)"' '0.207020442006996' '0.0107433672738621'
  '-0.072102214637485' '0.0456106275659727']
 ['"CDH2 (1000)"' '0.062191666745009' '-0.049808605031876'
  '0.0221367779349252' '0.0617088692131269']]


In [5]:
fileName = "D2_Achilles_gene_dep_scores_5by5.tsv"
np.savetxt(fileName, unitTestData, fmt='%s', delimiter='\t')

In [9]:
foo = np.array([[1., 1., 1.],
                [1., 0., 1.],
                [1., 1., 1.]
                ])

print(foo)
print(foo.astype(int))

print(foo.astype(bool))

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 0 1]
 [1 1 1]]
[[ True  True  True]
 [ True False  True]
 [ True  True  True]]
